user nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream activity_service {
        server farm-dora-activity-dev:8010;
    }

    upstream buyer_service {
        server farm-dora-buyer-dev:8020;
    }
        
    upstream search_service {
        server farm-dora-search-dev:8030;
    }
    
    upstream auth_service {
        server farm-dora-auth-dev:8040;
    }
    
    upstream product_service {
        server farm-dora-product-dev:8050;
    }

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;

    keepalive_timeout 65;

    map $uri $javascript_module_mime {
        ~*\.js$ "application/javascript";
        default "";
    }

    server {
        listen 80;
        server_name www.farm-dora.kro.kr farm-dora.kro.kr;

        location ~* \.(js|mjs)$ {
            root /usr/share/nginx/html;
            try_files $uri =404;
            add_header Content-Type application/javascript;
            add_header X-Content-Type-Options nosniff;
        }

        location /assets/ {
            root /usr/share/nginx/html;
            try_files $uri =404;
            add_header Content-Type application/javascript;
            add_header X-Content-Type-Options nosniff;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        location /api/activity/ {
            proxy_pass http://activity_service/api/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
        location /api/buyer/ {
            proxy_pass http://buyer_service/api/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
        location /api/search/ {
            proxy_pass http://search_service/api/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
        location /api/auth/ {
            proxy_pass http://auth_service/api/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
        location /api/product/ {
            proxy_pass http://product_service/api/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }

    include /etc/nginx/conf.d/*.conf;

    types {
        application/javascript js mjs;
    }

    map $sent_http_content_type $cors_header {
        "application/javascript" "*";
        default "";
    }
}